### ISSUE TITLE
Deleted class ServiceAccountValidator

### ISSUE THREAD

**Issue by dgomez94** [aporat/store-receipt-validator#37]
You have deleted the class ServiceAccountValidator but still being used in "README.md"

**Comment by thangytp** [comment]
Class 'ReceiptValidator\GooglePlay\ServiceAccountValidator' not found
have same problem

**Comment by KCErb** [comment]
It was deleted here: https://github.com/aporat/store-receipt-validator/commit/908220846736733ef9bd711aeacc4f8a752d9ef9

I'll be needing to use it in a project I'm on. Is a pull request welcome on the topic?

**Comment by KCErb** [comment]
By the way, the issue here is just that the readme is out of date. If you look at the "Google Play" example it is using a service account. Take a look at the first line of the config file used in the example here: https://github.com/aporat/store-receipt-validator/blob/master/examples/googleapi.json

I've been using it for a little while now and it's working well for me, thanks for the great library @aporat and for taking the time to create those examples!

**Comment by Stafox** [comment]
Guys, for now you don't need ServiceAccountValidator class.

Just use the following code.

```
        $googleClient = new \Google_Client();
        $googleClient->setScopes([\Google_Service_AndroidPublisher::ANDROIDPUBLISHER]);
        $googleClient->setApplicationName('Your_Purchase_Validator_Name');
        $googleClient->setAuthConfig($pathToServiceAccountJsonFile);

        $googleAndroidPublisher = new \Google_Service_AndroidPublisher($googleClient);
        $validator = new \ReceiptValidator\GooglePlay\Validator($googleAndroidPublisher);
```
